// Generated by gencpp from file ray_trace/ray_trace.msg
// DO NOT EDIT!


#ifndef RAY_TRACE_MESSAGE_RAY_TRACE_H
#define RAY_TRACE_MESSAGE_RAY_TRACE_H

#include <ros/service_traits.h>


#include <ray_trace/ray_traceRequest.h>
#include <ray_trace/ray_traceResponse.h>


namespace ray_trace
{

struct ray_trace
{

typedef ray_traceRequest Request;
typedef ray_traceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ray_trace
} // namespace ray_trace


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ray_trace::ray_trace > {
  static const char* value()
  {
    return "81c2826f4b1acbbe34aaa616c1b2d0b8";
  }

  static const char* value(const ::ray_trace::ray_trace&) { return value(); }
};

template<>
struct DataType< ::ray_trace::ray_trace > {
  static const char* value()
  {
    return "ray_trace/ray_trace";
  }

  static const char* value(const ::ray_trace::ray_trace&) { return value(); }
};


// service_traits::MD5Sum< ::ray_trace::ray_traceRequest> should match
// service_traits::MD5Sum< ::ray_trace::ray_trace >
template<>
struct MD5Sum< ::ray_trace::ray_traceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ray_trace::ray_trace >::value();
  }
  static const char* value(const ::ray_trace::ray_traceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ray_trace::ray_traceRequest> should match
// service_traits::DataType< ::ray_trace::ray_trace >
template<>
struct DataType< ::ray_trace::ray_traceRequest>
{
  static const char* value()
  {
    return DataType< ::ray_trace::ray_trace >::value();
  }
  static const char* value(const ::ray_trace::ray_traceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ray_trace::ray_traceResponse> should match
// service_traits::MD5Sum< ::ray_trace::ray_trace >
template<>
struct MD5Sum< ::ray_trace::ray_traceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ray_trace::ray_trace >::value();
  }
  static const char* value(const ::ray_trace::ray_traceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ray_trace::ray_traceResponse> should match
// service_traits::DataType< ::ray_trace::ray_trace >
template<>
struct DataType< ::ray_trace::ray_traceResponse>
{
  static const char* value()
  {
    return DataType< ::ray_trace::ray_trace >::value();
  }
  static const char* value(const ::ray_trace::ray_traceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAY_TRACE_MESSAGE_RAY_TRACE_H
